---
- name: "Upgrade the system"
  become: true
  apt:
    update_cache: true
    allow_unauthenticated: true
    upgrade: dist

- name: Installing packages
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: present
  register: result
  when:
    - install_debian_packages

