---
- import_tasks: tasks/debian/packages.yml
  when: install_debian_packages
  tags: ['apt', 'debian', 'packages']

- import_tasks: tasks/debian/dotfiles.yml
  when: setup_debian_config
  tags: ['apt', 'debian', 'packages']
