---
- name: DEBIAN - Upgrade the system
  become: true
  apt:
    update_cache: true
    allow_unauthenticated: true
    upgrade: dist

- name: DEBIAN - Installing packages
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: present
  register: result
