---
#TODO: Fix this to set up gem install paths on mac.

- hosts: all
  become: false
  vars:
    gem_list:
      - rubocop
      - solrgraph

  pre_tasks:
    - name: Ensuring gem is installed
      stat:
        path: /usr/bin/gem
      register: gem_check

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not gem_check.stat.exists

  tasks:
  - name: Upgrading Homebrew Packages
    homebrew:
      upgrade_all: "{{ gem_list }}"
    register: result
    until: result is successful
    when: gem_check.stat.exists
