---
dotfiles_repo: git@github.com:yuujay/dotfiles.git
dotfiles_repo_local_path: ~/.config/fish

# MAC Specific flags
install_homebrew_cask_packages: false
install_homebrew_if_missing: true
install_homebrew_packages: true
setup_mac: true
setup_mac_config: false
upgrade_homebrew_packages: false

# Debian Specific flags
install_debian_packages: false
setup_debian: false
setup_debian_config: false

# Generics
install_ruby_gems: false
setup_dot_files: false
setup_fish: false
setup_python: false
setup_ruby: false

apt_packages:
  - bash-completion
  - ctags
  - exa
  - fish
  - fzf
  - git
  - htop
  - jq
  - multitail
  - neovim
  - nmap
  - nodejs
  - npm
  - openssl
  - rsync
  - silversearcher-ag
  - tmux
  - tree
  - wget

brew_cask_packages:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - hammerspoon
  - iterm2
  - karabiner-elements
  - keycastr
  - kitty
  - ngork
  - slack
  - visual-studio-code

brew_packages:
  - bash-completion
  - bat
  - calcurse
  - cask
  - ctags
  - exa
  - fd
  - fish
  - fzf
  - gh
  - git
  - glow
  - go
  - htop
  - imagemagick
  - jq
  - minikube
  - multitail
  - neovim
  - nmap
  - nodejs
  - npm
  - openssl
  - rbenv
  - ripgrep
  - rsync
  - ruby-build
  - ssh-copy-id
  - the_silver_searcher
  - tmux
  - tree
  - wget
  - yarn

gem_list:
  - rubocop
  - solrgraph
  - neovim

npm_packages:
  - neovim

debian_file_overrides:
  - { src: '{{ dotfiles_repo_local_path }}/config/debian/config.fish', dest: '{{ dotfiles_repo_local_path }}/config.fish' }
  - { src: '{{ dotfiles_repo_local_path }}/config/debian/install.conf.yaml', dest: '{{ dotfiles_repo_local_path }}/install.conf.yaml' }
  - { src: '{{ dotfiles_repo_local_path }}/config/debian/tmux-shortcuts.conf', dest: '{{ dotfiles_repo_local_path }}/tmux/tmux-shortcuts.conf' }
  - { src: '{{ dotfiles_repo_local_path }}/config/debian/tmux-vim.conf', dest: '{{ dotfiles_repo_local_path }}/tmux/tmux-vim.conf' }

mac_file_overrides:
  - { src: '{{ dotfiles_repo_local_path }}/config/debian/config.fish', dest: '{{ dotfiles_repo_local_path }}/config.fish' }
  - { src: '{{ dotfiles_repo_local_path }}/config/debian/install.conf.yaml', dest: '{{ dotfiles_repo_local_path }}/install.conf.yaml' }
