---

- hosts: all
  become: false
  vars:
    brew_cask_packages:
      - docker
      - dropbox
      - firefox
      - google-chrome
      - iterm2
      - slack
      - visual-studio-code
    brew_packages:
      # - autoconf
      # - bash-completion
      # - docker-compose
      # - docker-machine
      - git
      # - git-lfs
      # - go
      # - jq
      # - nmap
      # - openssl
      # - packer
      # - python
      # - rbenv
      # - ruby-build
      # - ssh-copy-id
      # - tmux
      # - tree
      # - wget
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

  tasks:
  - name: Installing Homebrew Packages
    homebrew:
      name: "{{ brew_packages }}"
      state: present
    register: result
    until: result is successful
    when: homebrew_check.stat.exists
  # - name: Installing brew packages..
  #   brew:
  #     name: git
