---
- hosts: all

  vars_files:
    - default.config.yml

  tasks:
    - import_tasks: tasks/debian/main.yml
      tags: ['debian-dotfile', 'new-deb-machine']

    - import_tasks: tasks/mac/main.yml
      when: setup_mac
      tags: ['brew', 'packages']

    - import_tasks: tasks/ruby.yml
      when: setup_ruby
      tags: ['gems', 'ruby']

      # TODO: Fix this configuration
    - import_tasks: tasks/fish.yml
      when: setup_fish
      tags: ['shell', 'fish']
