---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 4"

jobs:

  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
          - macos-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Test dotbot install script
        run: sh dotbot-install

      - name: List brew path
        run: which brew

      - name: Install nvim
        run: brew install nvim

      - name: Checkhealth nvim
        run: nvim --clean -es '+:checkhealth'
