---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 4"

jobs:

  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
          - macos-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        
      - name: List files
        run: ls -al
        
      - name: Install stow
        run: brew install stow

      - name: Test stow install script
        run: sh stow-setup

      - name: Install nvim
        run: brew install nvim

      - name: Checkhealth nvim
        run: nvim --clean -es '+:checkhealth'
